= octobuild
Artem Navrotskiy; Marat Radchenko
:slug: bozaro/octobuild
:uri-project: https://github.com/{slug}
:uri-ci: {uri-project}/actions?query=branch%3Amaster
:uri-discuss: https://gitter.im/{slug}
:uri-unreal: https://github.com/EpicGames/UnrealEngine

image:https://img.shields.io/github/release/{slug}.svg[Download,link={uri-project}/releases/latest]
image:{uri-project}/workflows/CI/badge.svg?branch=master[Build Status,link={uri-ci}]
image:https://badges.gitter.im/{slug}.svg[Gitter chat,link={uri-discuss}]

[[overview]]
== Overview

This project allows you to speedup re-compilation of Unreal Engine (and UE-based games) by caching intermediate compilation files.

[[installation]]
== Installation

[[windows-installation]]
=== Windows

. Download https://github.com/bozaro/octobuild/releases/latest[MSI installer]
. Install it
. Normally build Unreal Engine projects, UBT will automatically use octobuild

[[ubuntu-installation]]
=== Ubuntu/Debian

. Download https://github.com/bozaro/octobuild/releases/latest[deb package]
. Install it via `dpkg -i <octobuild>.deb`
. Apply <<linux-notes,Linux patches>>
. Normally build Unreal Engine projects, UBT will automatically use octobuild

[[configuration]]
== Configuration files

You can get configuration files and show default and actual configuration by running `ib_console`/`xgConsole` without parameters.

[[benchmark]]
== Benchmark

Linux build tested on AMD Ryzen 7 3700X, 32GB DDR4 @ 3200MHz, SSD and Unreal Engine 5.0.3 by running `<engine>/Engine/Build/BatchFiles/RunUAT.sh <game>.uproject <game>Editor DebugGame Linux`.

Windows build tested on Intel Core i7-9700F, 32GB DDR4 @ 2400MHz, SSD and Unreal Engine 5.0.3 by running `<engine>/Engine/Build/BatchFiles/RunUBT.bat <game>.uproject <game>Editor DebugGame Win64`.

Console builds tested on Intel Core i7-9700F, 32GB DDR4 @ 2400MHz, SSD and Unreal Engine 5.0.3 by running `<engine>/Engine/Build/BatchFiles/RunUBT.bat <game>.uproject <game> DebugGame <platform>`.

[%autowidth]
|===
| Platform | Without octobuild | octobuild (0% cache) | octobuild (100% cache)

| *Linux*
| 3m54s
| 3m53s
| 36s

| *Win64 (MSVC 2019)*
| 8m4s
| 10m6s
| 2m15s

| *PS4*
| 6m12s
| 7m10s
| 2m34s

| *PS5*
| 5m48s
| 6m56s
| 2m11s

| *XB1*
| 4m40s
| 6m10s
| 1m39s

| *XSX*
| 4m49s
| 5m42s
| 1m40s

|===

[[linux-notes]]
== Linux notes

This project requires several patches to Unreal Engine:

* https://github.com/EpicGames/UnrealEngine/pull/9903[#9903]: Restore ability to use XGE executor on non-Windows platforms
* https://github.com/EpicGames/UnrealEngine/pull/9932[#9932]: Fix action graph copy action on non-Windows platforms
* https://github.com/EpicGames/UnrealEngine/pull/9933[#9933]: Reenable XGE on Linux
