= octobuild
Artem Navrotskiy; Marat Radchenko
:slug: octobuild/octobuild
:uri-project: https://github.com/{slug}
:uri-ci: {uri-project}/actions?query=branch%3Amain
:uri-discuss: https://gitter.im/{slug}
:source-highlighter: rouge

image:{uri-project}/actions/workflows/ci.yml/badge.svg?branch=main[Build Status,link={uri-ci}]
image:https://img.shields.io/github/release/{slug}.svg[Download,link={uri-project}/releases/latest]
image:https://img.shields.io/chocolatey/v/octobuild[Chocolatey package,link=https://community.chocolatey.org/packages/octobuild]
image:https://img.shields.io/winget/v/octobuild.octobuild[WinGet package,link=https://winstall.app/apps/octobuild.octobuild]
image:https://img.shields.io/homebrew/v/octobuild[Homebrew formula,link=https://formulae.brew.sh/formula/octobuild]

[[overview]]
== Overview

This project allows you to speedup re-compilation of Unreal Engine (and UE-based games) by caching intermediate compilation files, reducing time by <<benchmark,60-90%>>.

[[supported-platforms]]
== Supported platforms

- Android
- iOS
- Linux
- macOS
- PS4
- PS5
- Win64
- Xbox One
- Xbox Series

[[installation]]
== Installation

[[installation-windows-chocolatey]]
=== Chocolatey (Windows)

octobuild is available via https://community.chocolatey.org/packages/octobuild[Chocolatey] package manager.
If you already have Chocolatey installed, you can just run the following command from elevated console:

[source,powershell]
----
choco install octobuild
----

[[installation-windows-winget]]
=== WinGet (Windows)

[source,powershell]
----
winget install octobuild
----

[[installation-windows-manual]]
=== Manual (Windows)

. Download https://github.com/octobuild/octobuild/releases/latest[MSI installer]
. Double-click on it
. Next-next-next

[[installation-ubuntu-deb]]
=== deb package (Ubuntu 22.04, 24.04)

You can install octobuild on Ubuntu using the following commands:

[source,shell]
----
# Set up repository
curl -1sLf 'https://dl.cloudsmith.io/public/octobuild/octobuild/setup.deb.sh' | sudo -E bash

# Install octobuild
sudo apt-get install octobuild
----

[[installation-ubuntu-manual]]
=== Manual (Ubuntu/Debian)

. Download https://cloudsmith.io/~octobuild/repos/octobuild/packages/[deb package]
. Install it via `dpkg -i <octobuild>.deb`

[installation-homebrew]
=== Homebrew (macOS/Linux)

octobuild is available via https://brew.sh/[Homebrew package manager].

If you already have Homebrew configured, you can install octobuild with a single command:

[source,shell]
----
brew install octobuild
----

[[Usage]]
== Usage

You do not need to use octobuild directly.
Just build Unreal Engine as usual, via Unreal Build Tool, Unreal Automation Tool or your IDE.
Under the hood, they will automatically use octobuild.

Also see <<linux-notes>> and <<macos-notes>>.

[[clean-cache]]
== Cleaning cache

You can use `xgConsole /reset` command to clean octobuild cache.

[[configuration]]
== Configuration files

You can list configuration files and check actual configuration by running `ib_console`/`xgConsole` without parameters.

[%autowidth]
|===
| Platform | System-wide config | User-specific config (overrides system defaults)

| Linux
| `/etc/octobuild/octobuild.conf`
| `$XDG_CONFIG_HOME/octobuild/octobuild.conf` (with fallback to `~/.config/octobuild/octobuild.conf` when `$XDG_CONFIG_HOME` is not set)

| Windows
| `%ProgramData%\octobuild\octobuild.conf`
| `%AppData%\octobuild\octobuild.conf`

| macOS
| `/etc/octobuild/octobuild.conf`
| `~/Library/Application Support/octobuild/octobuild.conf`

|===

[[environment-variables]]
== Environment variables

Environment variables have higher priority than config files.

`OCTOBUILD_CACHE` (string):: specifies path to directory where octobuild cache is stored.
Default is `%LocalAppData%/octobuild/cache` on Windows, `~/.cache/octobuild` on Linux and `~/Library/Caches/octobuild` on macOS.
`OCTOBUILD_CACHE_LIMIT_MB` (number):: specifies octobuild disk cache size limit in megabytes.
Defaults is 64GB.
`OCTOBUILD_PROCESS_LIMIT` (number):: specifies max number of concurrent processes octobuild will spawn.
Default is number of cores.
`OCTOBUILD_USE_RESPONSE_FILES` (bool):: specifies whether octobuild should use compiler response files to overcome commandline length limitation.
Default is `true` on Windows and `false` on other platforms.
Enable this if you're getting `ERROR: The filename or extension is too long. (os error 206)` on Windows.
`OCTOBUILD_CACHE_MODE` (`ReadWrite`, `ReadOnly` or `None`):: controls octobuild cache mode.
`ReadWrite` is default normal operation.
`ReadOnly` allows to read existing files from cache, but doesn't write new files.
`None` completely disables cache.

[[benchmark]]
== Benchmark

Linux build tested on AMD Ryzen 7 3700X, 32GB DDR4 @ 3200MHz, SSD and Unreal Engine 5.0.3 by running `<engine>/Engine/Build/BatchFiles/RunUAT.sh <game>.uproject <game>Editor DebugGame Linux`.

Windows build tested on Intel Core i7-9700F, 32GB DDR4 @ 2400MHz, SSD and Unreal Engine 5.0.3 by running `<engine>/Engine/Build/BatchFiles/RunUBT.bat <game>.uproject <game>Editor DebugGame Win64`.

Console builds tested on Intel Core i7-9700F, 32GB DDR4 @ 2400MHz, SSD and Unreal Engine 5.0.3 by running `<engine>/Engine/Build/BatchFiles/RunUBT.bat <game>.uproject <game> DebugGame <platform>`.

[%autowidth]
|===
| Platform | Without octobuild | octobuild (0% cache) | octobuild (100% cache)

| *Linux*
| 3m54s
| 3m53s
| 36s

| *Win64 (MSVC 2019)*
| 8m4s
| 10m6s
| 2m15s

| *PS4*
| 6m12s
| 7m10s
| 2m34s

| *PS5*
| 5m48s
| 6m56s
| 2m11s

| *XB1*
| 4m40s
| 6m10s
| 1m39s

| *XSX*
| 4m49s
| 5m42s
| 1m40s

|===

[[linux-notes]]
== Linux notes

This project requires several patches to Unreal Engine:

- https://github.com/EpicGames/UnrealEngine/pull/9933[#9933]: Allow usage of octobuild on Linux
- https://github.com/EpicGames/UnrealEngine/pull/9903[#9903]: Restore ability to use XGE executor on non-Windows platforms (already included in UE >= 5.2)
- https://github.com/EpicGames/UnrealEngine/pull/9932[#9932]: Fix action graph copy action on non-Windows platforms (already included in UE >= 5.2)

[[macos-notes]]
== macOS notes

This project requires minor patching of Unreal Engine:

- https://github.com/EpicGames/UnrealEngine/pull/10191[#10191]: Allow usage of octobuild on macOS (already included in UE >= 5.3)
- https://github.com/EpicGames/UnrealEngine/pull/9903[#9903]: Restore ability to use XGE executor on non-Windows platforms (already included in UE >= 5.2)
- https://github.com/EpicGames/UnrealEngine/pull/9932[#9932]: Fix action graph copy action on non-Windows platforms (already included in UE >= 5.2)

== Building from source

. Install https://www.rust-lang.org/tools/install[Rust]
. (Windows only) Install Visual Studio 2019 or 2022. Enable "Desktop development with {cpp}" workload.
Also, enable "{cpp} 2019 Redistributable MSMs" "C++ 2022 Redistributable MSMs" in individual components.
. Clone octobuild Git repository
. Run `cargo build` in repository root to compile octobuild

[[uninstall]]
== Uninstall

[%autowidth]
|===
| Platform | Remove service | Delete app

| Linux
| TBD
| TBD

| Windows
| Search -> Services -> remove `Octobuild Agent`
| delete `%ProgramData%\octobuild`

| macOS
| TBD
| TBD

|===